[package]
name = "goku"
version = "0.1.0"
authors = ["k-nasa <htilcs1115@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { git="https://github.com/async-rs/async-std", features = ["unstable"] }
log = "0.4.8"
env_logger = "0.7.1"
