[package]
name = "goku"
version = "0.1.0"
authors = ["k-nasa <htilcs1115@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "0.99.11", features = ["unstable"] }
hyper = "0.13.0-alpha.4"
surf = { git="https://github.com/http-rs/surf" }
reqwest = "0.10.0-alpha.1"
