name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly, beta, stable]

    steps:
    - uses: actions/checkout@master

    - name: Cache rustup
      uses: actions/cache@v1
      with:
        path: ~/.rustup
        key: ${{runner.os}}-${{matrix.rust}}-toolchain

    - name: Cache cargo registry
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-

    - name: Cache deps crates
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/deps
        key: ${{ runner.os }}-${{ matrix.rust }}-target-deps-${{ hashFiles('**/Cargo.lock') }}-

    - name: Cache build
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/build
        key: ${{ runner.os }}-${{ matrix.rust }}-target-build-${{ hashFiles('**/Cargo.lock') }}-

    - name: Cache build
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/.fingerprint
        key: ${{ runner.os }}-${{ matrix.rust }}-target-fingerprint-${{ hashFiles('**/Cargo.lock') }}-

    - name: Cache cargo registry (on Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**\Cargo.lock') }}-

    - name: Cache deps crates (on Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/deps
        key: ${{ runner.os }}-${{ matrix.rust }}-target-deps-${{ hashFiles('**\Cargo.lock') }}-

    - name: Cache build (on Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/build
        key: ${{ runner.os }}-${{ matrix.rust }}-target-build-${{ hashFiles('**\Cargo.lock') }}-

    - name: Cache build (on Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/.fingerprint
        key: ${{ runner.os }}-${{ matrix.rust }}-target-fingerprint-${{ hashFiles('**\Cargo.lock') }}-

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all

    - name: bench
      uses: actions-rs/cargo@v1
      if: matrix.rust == 'nightly'
      with:
        command: build
        args: --benches

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

    - name: setup
      run: |
        rustup component add rustfmt
        rustc --version

    - name: Docs
      run: cargo doc
